# permissions for end users to view experiments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: llm-parameter-tuning
    app.kubernetes.io/managed-by: kustomize
  name: experiment-viewer-role
rules:
- apiGroups:
  - llmpt.kubedl.io.dinokli818.me
  resources:
  - experiments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - llmpt.kubedl.io.dinokli818.me
  resources:
  - experiments/status
  verbs:
  - get
